### ISSUE TITLE
New runLook returns large list instead of dataframe

### ISSUE THREAD

**Issue by chrispatrickcville** [looker/lookr#25]
I have a fairly simple look with 5 columns, including two pivot columns. Using the new sdk approach, I used runLook and got a large list of 20 elements: 

id, supports_pivot_in_db, null_sort_treatment, from_cache, expired, ran_at, pivots, sql, sql_explain, fields, fill_fields, has_totals, has_row_totals, applied_filters, applied_filter_expression, explore, timezone, data, errors, drill_menu_build_time

Each element in the "data" element is a row of the data (with a number of extra fields, such as $connector_referral.unconverted_ts_date$links[[1]]$url). I can extract the data values I need, but this is cumbersome and not behavior I was expecting. Is this due to using pivot columns?

**Comment by maxcorbin** [comment]
@chrispatrickcville You're mostly correct about the pivots. The new method is a bit cumbersome, but I left it in place to leave room for when people are using pivots in their query. I was going to return a `data.frame` for unpivoted queries and a list for pivoted queries, but I'm uneasy about returning a different data structure in a way that is hard to predict for the client, so they both return the whole response for now. You can limit the amount of extra fields that come through by setting the `resultFormat` to just `json` (the default is `json_detail`).

The short-term goal for the next release is for `runInlineQuery` and `runLook` drop a `data.frame` by default, but I am unsure of what to do with queries with pivots in them, since expanding the pivots could get messy. I'll update this issue when my indecision has been resolved!

**Comment by chrispatrickcville** [comment]
Thanks!

**Comment by shawnconnor** [comment]
In case it helps anyone, I did this to turn the json back into a dataframe:

```
get_look <- function(y) {
  look_json <- sdk$runLook(lookId = y, resultFormat = "json")
  out <- data.frame(do.call("rbind", lapply(look_json, function(x) {
    x[sapply(x, is.null)] <- NA
    unlist(x)
  })), stringsAsFactors = FALSE)
}

df <- get_look(1)
```

**Comment by chrispatrickcville** [comment]
Now it seems that the data structure is cleaned up, but I can't access the pivot columns any longer.

**Comment by maxcorbin** [comment]
I've pushed some changes to the `dev` branch that make the default behavior to crunch the data into a `data.frame` which works fine for pivoted and unpivoted Looks. It automatically expands each pivot column into its own column so this can potentially result in very wide `data.frame`s. I'll merge the change into the `master` branch at some point soon, but you can use it now by installing from the dev branch:

```
devtools::install_github("looker/lookr", ref="dev")
```

**Comment by chrispatrickcville** [comment]
I had the same issue

**Comment by tectoniccollinlooker** [comment]
Using the main lookr library this code worked like a charm:
`data <- sdk$runLook(lookId = 298)
df <-data.table::rbindlist(data, idcol = TRUE)`

Still error with `sdk$runInlineQuery`

**Comment by maxcorbin** [comment]
@chrispatrickcville @tectoniccollinlooker yep, my bad. i'm working on a fix right now that isn't a short term as the last one I pushed.

Unfortunately R doesn't have very many good tools for ensuring that your dev environment isn't being polluted by other things installed on your disk so I'm setting up a test environment in a VM right now to make sure my changes here won't break on machines other than mine.

I'll update as soon as the tests pass.

**Comment by maxcorbin** [comment]
hey thanks to the folks in this thread for being my guinea pigs here, I've pushed about a dozen more changes while testing different fixes on the vm and found one that works. i get a bunch of compilation errors while installing on a debian-based system but it didn't seem to get in the way of installing and running `runLook`

**Comment by chrispatrickcville** [comment]
Install works great for me now --- no errors

**Comment by tectoniccollinlooker** [comment]
For me, a few listed errors but it installed the library anyway and appears to be working fine.

And the `runInlineQuery()` works beautifully I am getting a data frame

**Comment by maxcorbin** [comment]
seems like the difference is between installing on a machine using `clang` as the C compiler vs. `gcc`/`g++`. I think `clang` doesn't show those errors. At any rate, seems like this is working ok. I'm going to close this issue and eventually up the version number and merge to master, since this might be a breaking change for some people
